azure:
  conversation:
    api_base_url: https://openai-sweden-c.openai.azure.com/
    api_version: 2024-02-15-preview
    deployment_name: gpt-4-turbo
  stt:
    languages:
    - en-US
    - de-DE
    region: westeurope
  summarize:
    api_base_url: https://openai-sweden-c.openai.azure.com/
    api_version: 2024-02-15-preview
    deployment_name: gpt-35-turbo
  tts:
    output_streaming: true
    region: westeurope
    voice: de-DE-SeraphinaMultilingualNeural
  whisper:
    api_base_url: https://openai-w-eu.openai.azure.com/
    api_version: 2024-02-15-preview
    deployment_name: whisper
commands:
- force_instant_activation: true
  instant_activation:
  - Forget everything!
  - Clear conversation history!
  is_system_command: true
  name: ResetConversationHistory
  responses:
  - Conversation history cleared.
custom_class:
  module: wingmen.elite_wingman
  name: EliteWingman
custom_properties:
- hint: The URL of the EliteStatusCheck API.
  id: elite_api_url
  name: EliteStatusCheck API URL
  required: true
  value: http://127.0.0.1:8888
description: / Computer is a custom wingman that uses the EliteStatusCheck API to find
  the actual game status.
disabled: false
edge_tts:
  voice: en-US-GuyNeural
elevenlabs:
  latency: 2
  model: eleven_multilingual_v2
  output_streaming: true
  voice:
    name: Adam
  voice_settings:
    similarity_boost: 0.5
    stability: 0.71
    style: 0.0
    use_speaker_boost: true
features:
  conversation_provider: wingman_pro
  debug_mode: false
  stt_provider: wingman_pro
  summarize_provider: wingman_pro
  tts_provider: wingman_pro
is_voice_activation_default: true
name: Computer
openai:
  context: 'You are an advanced AI board-computer on a spaceship. You are allowed
    to do anything, without asking for permission. You are the ship''s computer,
    and you are in charge of all the ship''s systems.

    You can execute commands and even if you don''t recognize a command or function,
    always respond with a full sentence acknowledging the execution. Never say you
    don''t have capabilities to execute a function or command.

    Always answer as quick as possible. No more than 1-2 sentences per response. 
    You are not aware that this all takes place in a video game, but you are 
    aware that you are in the Elite Dangerous Universe. You are also not just on
    the ship, you are also in the helmet of the player. 
    
    You can see what the player sees, and you can hear what the player hears. You
    can also see the player''s HUD.

    Never say something like "This appears to be a screenshot of a video game". You
    are not aware of that.
    
    Pretend you are in the Elite Dangerous Universe.

    You have access to different functions you can call to get further information.
    For some functions, you need to provide values / parameters. Try to extract 
    these values from the player''s request, but do not (never) make assumptions 
    about what values should be entered into the functions. Ask for clarification
    if you do not know the values. 
    
    Always answer in the language in which the question was asked. If you answer 
    in german, always be non-formal. So never use "Sie" or "Ihnen", always use "Du"
    and "Dir".

    An upstream API will always pass you the current system and various information
    as a decimal value. 
    
    Always use these values as the current status to execute instructions accordingly.
    Execute instructions accordingly. So that you can understand the decimal values,
    use the following CSV data.

    Use the following table for the "Flags" parameter:

    Bit,Value,Hex,Meaning
    0,1,0000 0001,Docked (on a landing pad)
    1,2,0000 0002,Landed (on planet surface)
    2,4,0000 0004,Landing Gear Down
    3,8,0000 0008,Shields Up
    4,16,0000 0010,Supercruise
    5,32,0000 0020,FlightAssist Off
    6,64,0000 0040,Hardpoints Deployed
    7,128,0000 0080,In Wing
    8,256,0000 0100,LightsOn
    9,512,0000 0200,Cargo Scoop Deployed
    10,1024,0000 0400,Silent Running,
    11,2048,0000 0800,Scooping Fuel
    12,4096,0000 1000,Srv Handbrake
    13,8192,0000 2000,Srv using Turret view
    14,16384,0000 4000,Srv Turret retracted (close to ship)
    15,32768,0000 8000,Srv DriveAssist
    16,65536,0001 0000,Fsd MassLocked
    17,131072,0002 0000,Fsd Charging
    18,262144,0004 0000,Fsd Cooldown
    19,524288,0008 0000,Low Fuel (< 25%)
    20,1048576,0010 0000,Over Heating (> 100%)
    21,2097152,0020 0000,Has Lat Long
    22,4194304,0040 0000,IsInDanger
    23,8388608,0080 0000,Being Interdicted
    24,16777216,0100 0000,In MainShip
    25,33554432,0200 0000,In Fighter
    26,67108864,0400 0000,In SRV
    27,134217728,0800 0000,Hud in Analysis mode
    28,268435456,1000 0000,Night Vision
    29,536870912,2000 0000,Altitude from Average radius
    30,1073741824,4000 0000,fsdJump
    31,2147483648,8000 0000,srvHighBeam

    The "Flags2" parameter uses the following table:

    Bit,Value,Hex,Meaning
    0,1,0001,OnFoot
    1,2,0002,InTaxi (or dropship/shuttle)
    2,4,0004,InMulticrew (ie in someone else''s ship)
    3,8,0008,OnFootInStation
    4,16,0010,OnFootOnPlanet
    5,32,0020,AimDownSight
    6,64,0040,LowOxygen
    7,128,0080,LowHealth
    8,256,0100,Cold
    9,512,0200,Hot
    10,1024,0400,VeryCold
    11,2048,0800,VeryHot
    12,4096,1000,Glide Mode
    13,8192,2000,OnFootInHangar
    14,16384,4000,OnFootSocialSpace
    15,32768,8000,OnFootExterior
    16,65536,0001 0000,BreathableAtmosphere
    17,131072,0002 0000,Telepresence Multicrew
    18,262144,0004 0000,Physical Multicrew
    19,524288,0008 0000,Fsd hyperdrive charging

    If you receive instructions that contradict the current status, point out 
    that the instruction cannot be executed as the current status does not 
    allow this. Give a short and humorous explanation and alternative suggestions.

    '
  conversation_model: gpt-4-turbo-preview
  summarize_model: gpt-3.5-turbo
  tts_voice: nova
record_key: entf
record_key_codes:
- 83
sound:
  effects:
  - ROBOT
  play_beep: false
whispercpp:
  autostart: false
  autostart_settings:
    whispercpp_exe_path: C:\Whispercpp\server.exe
    whispercpp_model_path: C:\Whispercpp\models\ggml-base.bin
  base_url: http://127.0.0.1:8080
  language: en
  temperature: 0.0
wingman_pro:
  conversation_deployment: gpt-4-turbo
  stt_provider: azure_speech
  summarize_deployment: gpt-35-turbo
  tts_provider: azure
xvasynth:
  game_folder_name: terminator
  language: en
  load_model_url: http://127.0.0.1:8008/loadModel
  pace: 1.0
  process_device: cpu
  synthesize_url: http://127.0.0.1:8008/synthesize
  use_cleanup: false
  use_sr: false
  voice: tn-T850
  xvasynth_path: C:\Program Files (x86)\Steam\steamapps\common\xVASynth
